In [18]:
import numpy as np
import pandas as pd

In [19]:
file_path='/content/drive/MyDrive/Classroom/인공지능 서비스 개발자 _ 강동1기/data/tmdb_5000_movies.csv'

In [20]:
movies=pd.read_csv(file_path)
movies.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [21]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [22]:
#필요한 변수(columns)만 추출
df=movies[['id', 'title', 'genres', 'vote_average','vote_count',  'popularity', 'overview','keywords', ]]
df.head(1)

id   title                                             genres  \
0  19995  Avatar  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

   vote_average  vote_count  popularity  \
0           7.2       11800  150.437577   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   

                                            keywords  
0  [{"id": 1463, "name": "culture clash"}, {"id":...

In [23]:
df['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [24]:
type(df['genres'][0])
#str 타입인 것을 확인, 리스트가 아니네?

str

In [27]:
#genres, keywords 컬럼 전처리(정제) 필요함 str << list

#문자열 파싱 라이브러리
from ast import literal_eval 

df['genres'].apply(literal_eval)
df['genres']=df['genres'].apply(literal_eval)
df['keywords']=df['keywords'].apply(literal_eval)

<ipython-input-27-9578a0cf8574>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres']=df['genres'].apply(literal_eval)
<ipython-input-27-9578a0cf8574>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['keywords']=df['keywords'].apply(literal_eval)


In [28]:
df['genres'][0]

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [30]:
type(df['genres'][0])
#str >> list 변환 확인

list

In [38]:
#list 내 여러개 dict의 name 키에 해당하는 값 리스트 변환
#key 값에 따른 value 값만 추출하고 싶당

df['genres'].apply(lambda x: [y['name'] for y in x])

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...                      
4798                        [Action, Crime, Thriller]
4799                                [Comedy, Romance]
4800               [Comedy, Drama, Romance, TV Movie]
4801                                               []
4802                                    [Documentary]
Name: genres, Length: 4803, dtype: object

In [32]:
dict_={'id': 28, 'name': 'Action'}
dict_['id']

28

In [40]:
df['genres']=df['genres'].apply(lambda x: [y['name'] for y in x])
df['keywords']=df['keywords'].apply(lambda x: [y['name'] for y in x])

<ipython-input-40-e03602b68edd>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres']=df['genres'].apply(lambda x: [y['name'] for y in x])
<ipython-input-40-e03602b68edd>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['keywords']=df['keywords'].apply(lambda x: [y['name'] for y in x])


In [41]:
df[['genres','keywords']][:1]

genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   

                                            keywords  
0  [culture clash, future, space war, space colon...

In [42]:
#장르 컨텐츠 유사도 측정

from sklearn.feature_extraction.text import CountVectorizer

In [45]:
#CountVectorizer
#1.문서 >> 토큰 리스트로 변환
#2. 각 문서에서 토큰 출현 빈도를 센다
#3. 각 문서를 BOW(bag of words:단어주머니) 인코딩 벡터

corpus=[
    'This is the first document.',
    'This is the second document.',
    'And the third one.',
    'is this the first document?',
    'The last document?'
]
vect=CountVectorizer()
vect.fit(corpus)
vect.vocabulary_ #빈도수를 세고 인덱스로 코딩

{'this': 9,
 'is': 3,
 'the': 7,
 'first': 2,
 'document': 1,
 'second': 6,
 'and': 0,
 'third': 8,
 'one': 5,
 'last': 4}

In [46]:
df['genres'][:5]

0    [Action, Adventure, Fantasy, Science Fiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
3                 [Action, Crime, Drama, Thriller]
4             [Action, Adventure, Science Fiction]
Name: genres, dtype: object

In [47]:
#CountVectorizer 적용하기 위해 공백문자로 word 단위로 구분되는 문자열로 변환

df['genres'].apply(lambda x: (' ').join(x))
#전처리단계에서 Science Fiction 을 붙인다

0       Action Adventure Fantasy Science Fiction
1                       Adventure Fantasy Action
2                         Action Adventure Crime
3                    Action Crime Drama Thriller
4               Action Adventure Science Fiction
                          ...                   
4798                       Action Crime Thriller
4799                              Comedy Romance
4800               Comedy Drama Romance TV Movie
4801                                            
4802                                 Documentary
Name: genres, Length: 4803, dtype: object

In [49]:
df['genre_literal']=df['genres'].apply(lambda x: (' ').join(x))
df['genre_literal'][:5]

<ipython-input-49-351949072017>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genre_literal']=df['genres'].apply(lambda x: (' ').join(x))


0    Action Adventure Fantasy Science Fiction
1                    Adventure Fantasy Action
2                      Action Adventure Crime
3                 Action Crime Drama Thriller
4            Action Adventure Science Fiction
Name: genre_literal, dtype: object

In [50]:
#CountVectorizer 로 학습
CountVectorizer(min_df=0,ngram_range=(1,2))
#min_df : 단어장에 들어갈 최소 빈도(초기화), ngram_range=(1,2): 1 <= n <= 2

CountVectorizer(min_df=0, ngram_range=(1, 2))

In [55]:
count_vec=CountVectorizer(min_df=0,ngram_range=(1,2))
count_vec.fit_transform(df['genre_literal'])

#4803*276 4803(영화의 개수) >> sparse matrix (행렬)
#276 차원을 1차원으로 나타내줌, 0이 너무 많은 행렬~, 흩어진 형태

<4803x276 sparse matrix of type '<class 'numpy.int64'>'
	with 20631 stored elements in Compressed Sparse Row format>

In [56]:
genre_mat=count_vec.fit_transform(df['genre_literal'])
print(genre_mat.shape)

(4803, 276)


In [57]:
print(genre_mat) #sparse matrix 만듦

  (0, 0)	1
  (0, 16)	1
  (0, 124)	1
  (0, 232)	1
  (0, 138)	1
  (0, 1)	1
  (0, 24)	1
  (0, 135)	1
  (0, 233)	1
  (1, 0)	1
  (1, 16)	1
  (1, 124)	1
  (1, 24)	1
  (1, 125)	1
  (2, 0)	1
  (2, 16)	1
  (2, 1)	1
  (2, 64)	1
  (2, 20)	1
  (3, 0)	1
  (3, 64)	1
  (3, 90)	1
  (3, 234)	1
  (3, 4)	1
  (3, 68)	1
  :	:
  (4796, 90)	1
  (4796, 234)	1
  (4796, 106)	1
  (4796, 144)	1
  (4797, 234)	1
  (4797, 153)	1
  (4797, 157)	1
  (4798, 0)	1
  (4798, 64)	1
  (4798, 234)	1
  (4798, 4)	1
  (4798, 78)	1
  (4799, 44)	1
  (4799, 214)	1
  (4799, 58)	1
  (4800, 90)	1
  (4800, 44)	1
  (4800, 214)	1
  (4800, 104)	1
  (4800, 50)	1
  (4800, 250)	1
  (4800, 182)	1
  (4800, 251)	1
  (4800, 229)	1
  (4802, 80)	1


In [58]:
#코사인 유사도 이용, 영화별 유사도 계산
from sklearn.metrics.pairwise import cosine_similarity

genre_sim=cosine_similarity(genre_mat,genre_mat)
print(genre_sim.shape)
print(genre_sim[:5])

(4803, 4803)
[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]
 [0.59628479 1.         0.4        ... 0.         0.         0.        ]
 [0.4472136  0.4        1.         ... 0.         0.         0.        ]
 [0.12598816 0.16903085 0.3380617  ... 0.12598816 0.         0.        ]
 [0.75592895 0.3380617  0.50709255 ... 0.         0.         0.        ]]


In [62]:
#argsort:자료를 정렬하는 것이 아님. 순서만 알고 싶을 때 사용
#유사도가 높은 영화를 앞에서부터 순서대로 보여줌
#0번째 영화의 경우 유사도 순서 : 0번, 3494번, 813번 . . . . 순서

genre_sim.argsort()[:,::-1] #내림차순 정리, 유사도가 높은것 >> 낮은것
# -->> 개별 영화 끼리의 유사도

genre_sim_sorted_ind=genre_sim.argsort()[:,::-1]

In [63]:
genre_sim_sorted_ind[:5]

array([[   0, 3494,  813, ..., 3038, 3037, 2401],
       [ 262,    1,  129, ..., 3069, 3067, 2401],
       [   2, 1740, 1542, ..., 3000, 2999, 2401],
       [2195, 1850, 3316, ...,  887, 2544, 4802],
       [ 102, 2995,   56, ..., 3046, 3045, 2401]])

In [64]:
#추천 ver1. 장르 코사인 유사도에 의해 영화를 추천하는 함수
#함수 분석
#인자로 입력된 df 데이터프레임에서 'title' 컬럼이 입력된 title_name 값인 데이터프레임 추출

condition=df['title']=='The Godfather'
df[condition]

id          title          genres  vote_average  vote_count  \
3337  238  The Godfather  [Drama, Crime]           8.4        5893   

      popularity                                           overview  \
3337  143.659698  Spanning the years 1945 to 1955, a chronicle o...   

                                               keywords genre_literal  
3337  [italy, love at first sight, loss of father, p...   Drama Crime

In [147]:
title_movie=df[condition]

#함수화
title_movie

id          title          genres  vote_average  vote_count  \
3337  238  The Godfather  [Drama, Crime]           8.4        5893   

      popularity                                           overview  \
3337  143.659698  Spanning the years 1945 to 1955, a chronicle o...   

                                               keywords genre_literal  \
3337  [italy, love at first sight, loss of father, p...   Drama Crime   

      weighted_vote  
3337       8.263591

In [66]:
#title_name 을 가진 데이터프레임에서 index 객체를 넘파이 이용 ndarray 반환
#sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n개의 index 추출


title_index=title_movie.index.values
title_index

array([3337])

In [67]:
genre_sim_sorted_ind
genre_sim_sorted_ind[title_index, :10]


array([[2731, 1243, 3636, 1946, 2640, 4065, 1847, 4217,  883, 3866]])

In [68]:
similar_indexes=genre_sim_sorted_ind[title_index, :10]
similar_indexes

array([[2731, 1243, 3636, 1946, 2640, 4065, 1847, 4217,  883, 3866]])

In [69]:
#추출된 top_n index 출력, top_n index 2차원 데이터
#데이터 프레임에서 index 사용하기 위해 2차원 array >> 1차원 array로 변경

similar_indexes.reshape(-1)

array([2731, 1243, 3636, 1946, 2640, 4065, 1847, 4217,  883, 3866])

In [72]:
similar_index=similar_indexes.reshape(-1)
similar_index

array([2731, 1243, 3636, 1946, 2640, 4065, 1847, 4217,  883, 3866])

In [74]:
df
df.iloc[similar_index]

id                                           title          genres  \
2731     240                          The Godfather: Part II  [Drama, Crime]   
1243     203                                    Mean Streets  [Drama, Crime]   
3636   36351                                   Light Sleeper  [Drama, Crime]   
1946   11699  The Bad Lieutenant: Port of Call - New Orleans  [Drama, Crime]   
2640     400         Things to Do in Denver When You're Dead  [Drama, Crime]   
4065  364083                                      Mi America  [Drama, Crime]   
1847     769                                      GoodFellas  [Drama, Crime]   
4217    9344                                            Kids  [Drama, Crime]   
883      640                             Catch Me If You Can  [Drama, Crime]   
3866     598                                     City of God  [Drama, Crime]   

      vote_average  vote_count  popularity  \
2731           8.3        3338  105.792936   
1243           7.2         345   17.002096   
3636           5.7          15    6.063868   
1946           6.0         326   17.339852   
2640           6.7          85    6.932221   
4065           0.0           0    0.039007   
1847           8.2        3128   63.654244   
4217           6.8         279   13.291991   
883            7.7        3795   73.944049   
3866           8.1        1814   44.356711   

                                               overview  \
2731  In the continuing saga of the Corleone crime f...   
1243  A small-time hood must choose from among love,...   
3636  A drug dealer with upscale clientele is having...   
1946  Terrence McDonagh, a New Orleans Police sergea...   
2640  A mafia film in Tarantino style with a star-st...   
4065  A hate-crime has been committed in a the small...   
1847  The true story of Henry Hill, a half-Irish, ha...   
4217  A controversial portrayal of teens in New York...   
883   A true story about Frank Abagnale Jr. who, bef...   
3866  Cidade de Deus is a shantytown that started du...   

                                               keywords genre_literal  
2731  [italo-american, cuba, vororte, melancholy, pr...   Drama Crime  
1243  [epilepsy, protection money, secret love, mone...   Drama Crime  
3636  [suicide, drug dealer, redemption, addict, exi...   Drama Crime  
1946  [police brutality, organized crime, policeman,...   Drama Crime  
2640  [father son relationship, bounty hunter, boat,...   Drama Crime  
4065                       [new york state, hate crime]   Drama Crime  
1847  [prison, based on novel, florida, 1970s, mass ...   Drama Crime  
4217                              [puberty, first time]   Drama Crime  
883   [con man, biography, fbi agent, overhead camer...   Drama Crime  
3866  [male nudity, street gang, brazilian, photogra...   Drama Crime

In [81]:
#실제 함수
#sorted_ind,title_name 은 변수 설정
def find_sim_movie_ver1(df,sorted_ind,title_name,top_n=10):
  #인자로 입력된 df 데이터프레임에서 'title' 컬럼이 입력된 title_name 값인 데이터프레임 추출
  title_movie=df[df['title']==title_name]
  #title_name 을 가진 데이터프레임의 index 객체를 ndarray 로 반환하고
  #sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n개의 index 추출

  title_index=title_movie.index.values
  similar_indexes=sorted_ind[title_index,:(top_n)]

  #추출된 top_n index를 출력(2차원)
  #데이터프레임에서 index로 사용하기 위해서는 1차원 array로 변경

  print(similar_indexes)

  #2차원 >> 1차원
  similar_index=similar_indexes.reshape(-1)

  return df.iloc[similar_index]


In [82]:
#영화 God Father와 장르가 유사한 영화 10개 추천

similar_movies=find_sim_movie_ver1(df,genre_sim_sorted_ind,'The Godfather',10)
similar_movies

[[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]]


id                                           title          genres  \
2731     240                          The Godfather: Part II  [Drama, Crime]   
1243     203                                    Mean Streets  [Drama, Crime]   
3636   36351                                   Light Sleeper  [Drama, Crime]   
1946   11699  The Bad Lieutenant: Port of Call - New Orleans  [Drama, Crime]   
2640     400         Things to Do in Denver When You're Dead  [Drama, Crime]   
4065  364083                                      Mi America  [Drama, Crime]   
1847     769                                      GoodFellas  [Drama, Crime]   
4217    9344                                            Kids  [Drama, Crime]   
883      640                             Catch Me If You Can  [Drama, Crime]   
3866     598                                     City of God  [Drama, Crime]   

      vote_average  vote_count  popularity  \
2731           8.3        3338  105.792936   
1243           7.2         345   17.002096   
3636           5.7          15    6.063868   
1946           6.0         326   17.339852   
2640           6.7          85    6.932221   
4065           0.0           0    0.039007   
1847           8.2        3128   63.654244   
4217           6.8         279   13.291991   
883            7.7        3795   73.944049   
3866           8.1        1814   44.356711   

                                               overview  \
2731  In the continuing saga of the Corleone crime f...   
1243  A small-time hood must choose from among love,...   
3636  A drug dealer with upscale clientele is having...   
1946  Terrence McDonagh, a New Orleans Police sergea...   
2640  A mafia film in Tarantino style with a star-st...   
4065  A hate-crime has been committed in a the small...   
1847  The true story of Henry Hill, a half-Irish, ha...   
4217  A controversial portrayal of teens in New York...   
883   A true story about Frank Abagnale Jr. who, bef...   
3866  Cidade de Deus is a shantytown that started du...   

                                               keywords genre_literal  
2731  [italo-american, cuba, vororte, melancholy, pr...   Drama Crime  
1243  [epilepsy, protection money, secret love, mone...   Drama Crime  
3636  [suicide, drug dealer, redemption, addict, exi...   Drama Crime  
1946  [police brutality, organized crime, policeman,...   Drama Crime  
2640  [father son relationship, bounty hunter, boat,...   Drama Crime  
4065                       [new york state, hate crime]   Drama Crime  
1847  [prison, based on novel, florida, 1970s, mass ...   Drama Crime  
4217                              [puberty, first time]   Drama Crime  
883   [con man, biography, fbi agent, overhead camer...   Drama Crime  
3866  [male nudity, street gang, brazilian, photogra...   Drama Crime

In [83]:
similar_movies.columns

Index(['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity',
       'overview', 'keywords', 'genre_literal'],
      dtype='object')

In [87]:
similar_movies[['title', 'vote_average', 'vote_count','genres']]

#문제 : 평점(vote_average)기반, 추천하고자 했는데 vote_count 가 낮은 영화는 제외하고 싶어!

title  vote_average  \
2731                          The Godfather: Part II           8.3   
1243                                    Mean Streets           7.2   
3636                                   Light Sleeper           5.7   
1946  The Bad Lieutenant: Port of Call - New Orleans           6.0   
2640         Things to Do in Denver When You're Dead           6.7   
4065                                      Mi America           0.0   
1847                                      GoodFellas           8.2   
4217                                            Kids           6.8   
883                              Catch Me If You Can           7.7   
3866                                     City of God           8.1   

      vote_count          genres  
2731        3338  [Drama, Crime]  
1243         345  [Drama, Crime]  
3636          15  [Drama, Crime]  
1946         326  [Drama, Crime]  
2640          85  [Drama, Crime]  
4065           0  [Drama, Crime]  
1847        3128  [Drama, Crime]  
4217         279  [Drama, Crime]  
883         3795  [Drama, Crime]  
3866        1814  [Drama, Crime]

In [88]:
df
df.columns

Index(['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity',
       'overview', 'keywords', 'genre_literal'],
      dtype='object')

In [92]:
#평점기준으로 정렬(sort_values)해보니, 평가횟수(vote_count)가 낮은 것들도 포함되어 있음
#-->> 그러므로 평가 횟수를 반영한 평점(가중평점)이 필요함. 내림차순으로 상위 10개만 추출
df[['title', 'genres', 'vote_average', 'vote_count']].sort_values('vote_average', ascending=False)[:10]


title                             genres  \
3519          Stiff Upper Lips                           [Comedy]   
4247     Me You and Five Bucks           [Romance, Comedy, Drama]   
4045     Dancer, Texas Pop. 81            [Comedy, Drama, Family]   
4662            Little Big Top                           [Comedy]   
3992                 Sardaarji                                 []   
2386            One Man's Hero  [Western, Action, Drama, History]   
2970        There Goes My Baby                    [Drama, Comedy]   
1881  The Shawshank Redemption                     [Drama, Crime]   
2796     The Prisoner of Zenda        [Adventure, Drama, Romance]   
3337             The Godfather                     [Drama, Crime]   

      vote_average  vote_count  
3519          10.0           1  
4247          10.0           2  
4045          10.0           1  
4662          10.0           1  
3992           9.5           2  
2386           9.3           2  
2970           8.5           2  
1881           8.5        8205  
2796           8.4          11  
3337           8.4        5893

In [93]:
##(매우 중요) CBF 활용시 적용해야 할 코드

#가중평점(평점,평가횟수) 반영한 영화 추천

In [100]:
# 상위 60% 에 해당하는 vote_count 최소 투표 횟수인 m 으로 지정
df['vote_average']
df['vote_average'].mean()

C=df['vote_average'].mean()
print(C)
#전체 영화에 대한 평점 6.092 

df['vote_count'].quantile(0.6)
m=df['vote_count'].quantile(0.6)
print(m)
#370.1999999999998 -->> 적어도 370번 이상 평점을 준 영화의 평점을 사용(투표수 370번 이상)

6.092171559442016
370.1999999999998


In [128]:
#C:전체 영화에 대한 평균 평점 : 약 6점
#m:평점을 부여하기 위한 최소 투표 회수 = 370회(상위 60% 수준)

print('C: ',round(C,2),'점', 'm: ',round(m,2),'회')

C:  6.09 점 m:  370.2 회


In [132]:
#가중 평점을 계산하는 함수
def weighted_vote_average(record):
  v=record['vote_count']
  R=record['vote_average']

  return (((v/(v+m))*R) + ((m/(m+v))*C))

In [133]:
#기존 데이터에 가중평점 컬럼 추가

df.apply(weighted_vote_average, axis=1)
df['weighted_vote']=df.apply(weighted_vote_average, axis=1)

<ipython-input-133-183814f8d92e>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weighted_vote']=df.apply(weighted_vote_average, axis=1)


In [134]:
#가중평균 기준, 영화 순위 추출(내림차순)>>평점이 높은 영화 먼저 출력

df.columns

Index(['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity',
       'overview', 'keywords', 'genre_literal', 'weighted_vote'],
      dtype='object')

In [135]:
df[['weighted_vote','title','vote_average','vote_count','genres']]
df[['weighted_vote','title','vote_average','vote_count','genres']].sort_values('weighted_vote', ascending=False)[:10]

weighted_vote                     title  vote_average  vote_count  \
1881       8.396052  The Shawshank Redemption           8.5        8205   
3337       8.263591             The Godfather           8.4        5893   
662        8.216455                Fight Club           8.3        9413   
3232       8.207102              Pulp Fiction           8.3        8428   
65         8.136930           The Dark Knight           8.2       12002   
1818       8.126069          Schindler's List           8.3        4329   
3865       8.123248                  Whiplash           8.3        4254   
809        8.105954              Forrest Gump           8.2        7927   
2294       8.105867             Spirited Away           8.3        3840   
2731       8.079586    The Godfather: Part II           8.3        3338   

                                       genres  
1881                           [Drama, Crime]  
3337                           [Drama, Crime]  
662                                   [Drama]  
3232                        [Thriller, Crime]  
65           [Drama, Action, Crime, Thriller]  
1818                    [Drama, History, War]  
3865                                  [Drama]  
809                  [Comedy, Drama, Romance]  
2294  [Fantasy, Adventure, Animation, Family]  
2731                           [Drama, Crime]

In [136]:
##추천 ver2 먼저 장르 유사성 높은 영화 20개 선정 후, 가중평점 순으로 10개 선정

def find_sim_movie_ver2(df, sorted_ind, title_name, top_n=10):
  title_movie= df[df['title']==title_name]
  title_index=title_movie.index.values

  #top_n의 2배 (유사성 높은 영화 20개 선정 위함)에 해당하는 장르 유사성이 높은 index 추출
  similar_indexes=sorted_ind[title_index, :(top_n*2)]
  similar_index=similar_indexes.reshape(-1)

  #기준 영화 index는 제외(기존에 본 영화 제외하고 추천하기 위함. title_index 겹치지않는영화 추천)
  similar_index=similar_index[similar_index != title_index]

  #top_n의 2배(후보군)에서 weighted_vote 높은 순으로 top_n 만큼 추출
  return df.iloc[similar_index].sort_values('weighted_vote', ascending=False)[:top_n]





In [137]:
#영화 The Godfather에 대한 장르 유사성, 가중평점 반영한 영화 10편을 추천
similar_movies=find_sim_movie_ver2(df, genre_sim_sorted_ind, 'The Godfather',10)
similar_movies

id                        title          genres  vote_average  \
2731     240       The Godfather: Part II  [Drama, Crime]           8.3   
1847     769                   GoodFellas  [Drama, Crime]           8.2   
3866     598                  City of God  [Drama, Crime]           8.1   
1663     311  Once Upon a Time in America  [Drama, Crime]           8.2   
883      640          Catch Me If You Can  [Drama, Crime]           7.7   
281     4982            American Gangster  [Drama, Crime]           7.4   
4041   11798              This Is England  [Drama, Crime]           7.4   
1149  168672              American Hustle  [Drama, Crime]           6.8   
1243     203                 Mean Streets  [Drama, Crime]           7.2   
2839   10220                     Rounders  [Drama, Crime]           6.9   

      vote_count  popularity  \
2731        3338  105.792936   
1847        3128   63.654244   
3866        1814   44.356711   
1663        1069   49.336397   
883         3795   73.944049   
281         1502   42.361215   
4041         363    8.395624   
1149        2807   49.664128   
1243         345   17.002096   
2839         439   18.422008   

                                               overview  \
2731  In the continuing saga of the Corleone crime f...   
1847  The true story of Henry Hill, a half-Irish, ha...   
3866  Cidade de Deus is a shantytown that started du...   
1663  A former Prohibition-era Jewish gangster retur...   
883   A true story about Frank Abagnale Jr. who, bef...   
281   Following the death of his employer and mentor...   
4041  A story about a troubled boy growing up in Eng...   
1149  A con man, Irving Rosenfeld, along with his se...   
1243  A small-time hood must choose from among love,...   
2839  A young man is a reformed gambler who must ret...   

                                               keywords genre_literal  \
2731  [italo-american, cuba, vororte, melancholy, pr...   Drama Crime   
1847  [prison, based on novel, florida, 1970s, mass ...   Drama Crime   
3866  [male nudity, street gang, brazilian, photogra...   Drama Crime   
1663  [life and death, corruption, street gang, rape...   Drama Crime   
883   [con man, biography, fbi agent, overhead camer...   Drama Crime   
281   [underdog, black people, drug traffic, drug sm...   Drama Crime   
4041  [holiday, skinhead, england, vandalism, indepe...   Drama Crime   
1149             [con artist, scam, mobster, fbi agent]   Drama Crime   
1243  [epilepsy, protection money, secret love, mone...   Drama Crime   
2839  [gambling, law, compulsive gambling, roulette,...   Drama Crime   

      weighted_vote  
2731       8.079586  
1847       7.976937  
3866       7.759693  
1663       7.657811  
883        7.557097  
281        7.141396  
4041       6.739664  
1149       6.717525  
1243       6.626569  
2839       6.530427

In [142]:
similar_movies[['title','vote_average','weighted_vote','genres','vote_count']]
result=similar_movies[['title','vote_average','weighted_vote','genres','vote_count']]
result

title  vote_average  weighted_vote  \
2731       The Godfather: Part II           8.3       8.079586   
1847                   GoodFellas           8.2       7.976937   
3866                  City of God           8.1       7.759693   
1663  Once Upon a Time in America           8.2       7.657811   
883           Catch Me If You Can           7.7       7.557097   
281             American Gangster           7.4       7.141396   
4041              This Is England           7.4       6.739664   
1149              American Hustle           6.8       6.717525   
1243                 Mean Streets           7.2       6.626569   
2839                     Rounders           6.9       6.530427   

              genres  vote_count  
2731  [Drama, Crime]        3338  
1847  [Drama, Crime]        3128  
3866  [Drama, Crime]        1814  
1663  [Drama, Crime]        1069  
883   [Drama, Crime]        3795  
281   [Drama, Crime]        1502  
4041  [Drama, Crime]         363  
1149  [Drama, Crime]        2807  
1243  [Drama, Crime]         345  
2839  [Drama, Crime]         439

In [146]:
#Spider-Man 3 종아하는 사람기준. 장르 유사한 영화 추천해 주세요
spiderman3=find_sim_movie_ver2(df, genre_sim_sorted_ind, 'Spider-Man 3',10)
spiderman3[['title','vote_average','weighted_vote','genres','vote_count']]

title  vote_average  \
329      The Lord of the Rings: The Return of the King           8.1   
262  The Lord of the Rings: The Fellowship of the Ring           8.0   
330              The Lord of the Rings: The Two Towers           8.0   
19           The Hobbit: The Battle of the Five Armies           7.1   
98                   The Hobbit: An Unexpected Journey           7.0   
126                               Thor: The Dark World           6.8   
30                                        Spider-Man 2           6.7   
129                                               Thor           6.6   
20                              The Amazing Spider-Man           6.5   
38                            The Amazing Spider-Man 2           6.5   

     weighted_vote                        genres  vote_count  
329       8.011871  [Adventure, Fantasy, Action]        8064  
262       7.922175  [Adventure, Fantasy, Action]        8705  
330       7.910111  [Adventure, Fantasy, Action]        7487  
19        7.027274  [Action, Adventure, Fantasy]        4760  
98        6.961224  [Adventure, Fantasy, Action]        8297  
126       6.748873  [Action, Adventure, Fantasy]        4755  
30        6.652034  [Action, Adventure, Fantasy]        4321  
129       6.572735  [Adventure, Fantasy, Action]        6525  
20        6.478296  [Action, Adventure, Fantasy]        6586  
38        6.466812  [Action, Adventure, Fantasy]        4179

In [148]:
#넘파이 argsort
import numpy as np
np.array([1.5,0.2,4.2,2.5])

array([1.5, 0.2, 4.2, 2.5])

In [150]:
a=np.array([1.5,0.2,4.2,2.5])
a.argsort() #순서만 알려줌,위치정보안내, 정렬했을때의 위치

#a:정렬되지 않은 숫자 array
#a.argsort() array a를 정렬하는 인덱스의 array

array([1, 0, 3, 2])

In [152]:
s=a.argsort()
a[s]
#정렬되어서 나타남. 오름차순

array([0.2, 1.5, 2.5, 4.2])

In [153]:
print(a)
print(s)

[1.5 0.2 4.2 2.5]
[1 0 3 2]


In [154]:
#내림차순정렬
a[s[::-1]]

array([4.2, 2.5, 1.5, 0.2])