1. 넘파이 연산(복습할까요?)


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import numpy as np
import pandas as pd

In [3]:
A=np.array([
    [3,3,2,3,1],
    [5,3,2,9,8],
    [1,4,8,7,5],
    [5,7,5,9,3]
])

In [4]:
B=np.array([
    [1,7,7,2,3],
    [5,8,8,8,8],
    [9,5,9,7,6],
    [6,7,2,2,2]
])

In [5]:
np.sum(A)

93

In [6]:
A+B

array([[ 4, 10,  9,  5,  4],
       [10, 11, 10, 17, 16],
       [10,  9, 17, 14, 11],
       [11, 14,  7, 11,  5]])

In [7]:
A-B

array([[ 2, -4, -5,  1, -2],
       [ 0, -5, -6,  1,  0],
       [-8, -1, -1,  0, -1],
       [-1,  0,  3,  7,  1]])

In [8]:
A*B
#넘파이라 가능한 연산, 내적 불가

array([[ 3, 21, 14,  6,  3],
       [25, 24, 16, 72, 64],
       [ 9, 20, 72, 49, 30],
       [30, 49, 10, 18,  6]])

In [9]:
A/B

array([[3.        , 0.42857143, 0.28571429, 1.5       , 0.33333333],
       [1.        , 0.375     , 0.25      , 1.125     , 1.        ],
       [0.11111111, 0.8       , 0.88888889, 1.        , 0.83333333],
       [0.83333333, 1.        , 2.5       , 4.5       , 1.5       ]])

In [10]:
#A @ B
A@B.T

array([[ 47,  87,  87,  51],
       [ 82, 201, 189,  89],
       [114, 197, 180,  74],
       [116, 217, 206, 113]])

In [11]:
C=np.array([
    [3,3,2,3,1],
    [5,3,2,9,8],
    [1,4,np.nan,7,5],
    [5,7,5,9,3]
])

In [12]:
D=np.array([
    [1,np.nan,7,2,3],
    [5,8,8,8,8],
    [9,5,9,7,6],
    [np.nan,7,2,2,2]
])

In [13]:
C+D

array([[ 4., nan,  9.,  5.,  4.],
       [10., 11., 10., 17., 16.],
       [10.,  9., nan, 14., 11.],
       [nan, 14.,  7., 11.,  5.]])

In [14]:
5*C

array([[15., 15., 10., 15.,  5.],
       [25., 15., 10., 45., 40.],
       [ 5., 20., nan, 35., 25.],
       [25., 35., 25., 45., 15.]])

In [15]:
C

array([[ 3.,  3.,  2.,  3.,  1.],
       [ 5.,  3.,  2.,  9.,  8.],
       [ 1.,  4., nan,  7.,  5.],
       [ 5.,  7.,  5.,  9.,  3.]])

In [16]:
sum(C)
#열값 연산

array([14., 17., nan, 28., 17.])

In [17]:
np.sum(C)

nan

In [18]:
np.nansum(C)
#nan 값을 제외하고 계산

85.0

In [19]:
A=np.array([
    [3,3,2,3,1],
    [5,3,2,9,8],
    [1,4,8,7,5],
    [5,7,5,9,3]
])

np.mean(A)

4.65

In [20]:
np.nanmean(C)

4.473684210526316

In [21]:
print(A[0])
print(A[3])

[3 3 2 3 1]
[5 7 5 9 3]


In [22]:
#열 접근법
A[:,3]

array([3, 9, 7, 9])

넘파이 활용, user(사용자) 간 거리 구하기

In [23]:
import numpy as np
import pandas as pd
from math import sqrt

In [24]:
user_1=np.array([0,1,2,3,4,5])
user_2=np.array([0,1,4,6,1,4])

def distance(user_1,user_2):
  ''' 유클리드 거리를 계산해 주는 함수 '''
  #코드를 쓰세요
  result=np.sqrt(np.sum((user_1-user_2)**2))

  return result
  #print('result(user_1,user2)=',result)

  #실행코드
  #user_1=np.array([0,1,2,3,4,5])
  #user_2=np.array([0,1,4,6,1,4])

In [25]:
distance(user_1,user_2)

4.795831523312719

In [26]:
np.array([0,1,2,3,4,5])

array([0, 1, 2, 3, 4, 5])

In [27]:
#두 사용자(user) 배열 형태
#두 사용자 간의 거리(각 원소의 차이)

#user_1-user_2 제곱을 다 더해서 루트

협업필터링 넘파이 활용, 이웃들 구하기

In [28]:
#/content/drive/MyDrive/Classroom/인공지능 서비스 개발자 _ 강동1기/data/cf_ratings.csv

In [29]:
path='/content/drive/MyDrive/Classroom/인공지능 서비스 개발자 _ 강동1기/data/cf_ratings.csv'

#소수점 2째자리까지만 출력
np.set_printoptions(precision=2)

In [30]:
def distance(user_1,user_2):
  return np.sqrt(np.sum((user_1-user_2)**2))

In [31]:
#np.isnan(rating)

In [32]:
#movie_id 번째 영화를 평가하지 않은 사용자 미리 제외하는 함수 생성
def filter_users_without_movie(rating_data,movie_id):
  return rating_data[~np.isnan(rating_data[:,movie_id])]

In [51]:
#평점 데이터의 빈 값을 각 사용자(유저) 평균값으로 채우는 함수 생성

def fill_nan_with_user_mean(rating_data):
  #평점 데이터 원본 훼손하지 않기 위해 복사를함
  filled_data=np.copy(rating_data)
  
  #사용자(유저)의 평균 평점 계산
  row_mean=np.nanmean(filled_data,axis=1)

  #비어있는 인덱스 구하기
  inds=np.where(np.isnan(filled_data))

  #빈 인덱스를 유저 평균 평점으로 채우기
  filled_data[inds]=np.take(row_mean, inds[0])

  return filled_data


In [55]:
#user_id에 해당하는 사용자(유저) 이웃을 찾아주는 함수
def get_k_neighbors(user_id,rating_data,k):
  #평점 데이터 원본 훼손하지 않기 위해 복사를함
  distance_data=np.copy(rating_data)

  #마지막에 거리 데이터 담을 열 한 개 추가
  distance_data=np.append(distance_data,np.zeros((distance_data.shape[0],1)), axis=1)

  for i in range(len(distance_data)):
    row=distance_data[i]
    
    #반복문을 돌면서 user_id번째 유저가 나올 때는 
    #해당 데이터의 거리 정보는 무한대인 np.inf로 저장함

    if i == user_id:
      #같은 유저면 거리를 무한대로 설정
      #같은 유저라도 고유위치를 갖고있을 수 있기때문에 오류가 생기지 않기위해서 inf 로 설정
      row[-1]=np.inf      
    else:
      #같은 유저가 아니라면 끝자리에 넣어줘
      #distance 는 거리구하는 함수(위에서 정의)
      row[-1]=distance(distance_data[user_id][:-1],row[:-1])

  #데이터를 거리 열 기준 정렬, argsort 하는 순간 내림차순으로 정렬
  distance_data[np.argsort(distance_data[:,-1])]

  #가장 가까운 k개의 행 리턴
  #단, 마지막(거리) 열은 제외한다
  return distance_data[:k,:-1]


In [52]:
#실행 코드
#영화 3을 본 유저들 중, 유저 0과 비슷한 유저를 5명 찾으세요.

#1.평점 데이터를 불러옴
#index_col 인덱스를 user_id으로 지정
pd.read_csv(path,index_col='user_id')
rating_data=pd.read_csv(path,index_col='user_id').values
print(rating_data)
print()

#2. 3번째 영화를 보지 않은 유저를 데이터에서 미리 제외시킨다
filltered_data=filter_users_without_movie(rating_data,3)

#3. 빈 값들이 채워진 새로운 행렬 생성
filled_data=fill_nan_with_user_mean(filltered_data)
print(filled_data)




[[ 2.  3.  4. nan  2.  3. nan nan nan  4.  4. nan nan  1. nan nan  2.  5.
   2. nan]
 [nan nan nan  4. nan  5. nan nan  2. nan  4. nan  1. nan nan nan nan  5.
  nan nan]
 [ 2. nan  1. nan nan  5.  5. nan nan nan nan  5.  3.  3. nan  3.  3.  4.
  nan nan]
 [nan  3.  5. nan nan nan  4.  3. nan  5.  3. nan  4. nan nan  2. nan nan
  nan  2.]
 [nan nan nan  5. nan nan  2.  2.  2. nan  3.  4.  2.  5.  4. nan nan nan
   4.  2.]
 [nan  4.  3. nan nan  5. nan nan nan  3.  2. nan nan nan  1. nan  4.  3.
  nan  5.]
 [ 3. nan nan nan  4.  5.  2.  2. nan  3. nan  4. nan nan  2.  4. nan nan
  nan  1.]
 [nan  5.  1.  4. nan nan nan  3.  1. nan  1. nan nan  4. nan nan  2. nan
  nan  4.]
 [nan  3.  1.  1. nan  3. nan  4. nan  1.  1. nan  4.  4.  2. nan nan  5.
   3. nan]
 [ 1.  1. nan  1.  1. nan nan nan nan nan nan  2. nan nan  1. nan nan nan
   4. nan]
 [nan  2. nan nan  2.  2. nan nan  2.  3.  2. nan nan  1.  4.  5.  3. nan
   3.  3.]
 [ 3. nan nan  5.  4. nan nan  4.  5.  3. nan  1.  2.  1.  1. nan

In [56]:
#영화 3을 본 유저들 중 유저 0과 비슷한 유저를 5명 찾으세요.
get_k_neighbors(0,filled_data,5)

array([[3.5 , 3.5 , 3.5 , 4.  , 3.5 , 5.  , 3.5 , 3.5 , 2.  , 3.5 , 4.  ,
        3.5 , 1.  , 3.5 , 3.5 , 3.5 , 3.5 , 5.  , 3.5 , 3.5 ],
       [3.18, 3.18, 3.18, 5.  , 3.18, 3.18, 2.  , 2.  , 2.  , 3.18, 3.  ,
        4.  , 2.  , 5.  , 4.  , 3.18, 3.18, 3.18, 4.  , 2.  ],
       [2.78, 5.  , 1.  , 4.  , 2.78, 2.78, 2.78, 3.  , 1.  , 2.78, 1.  ,
        2.78, 2.78, 4.  , 2.78, 2.78, 2.  , 2.78, 2.78, 4.  ],
       [2.67, 3.  , 1.  , 1.  , 2.67, 3.  , 2.67, 4.  , 2.67, 1.  , 1.  ,
        2.67, 4.  , 4.  , 2.  , 2.67, 2.67, 5.  , 3.  , 2.67],
       [1.  , 1.  , 1.57, 1.  , 1.  , 1.57, 1.57, 1.57, 1.57, 1.57, 1.57,
        2.  , 1.57, 1.57, 1.  , 1.57, 1.57, 1.57, 4.  , 1.57]])

In [38]:
#참고
n=3
np.zeros((n,1))

array([[0.],
       [0.],
       [0.]])