In [2]:
import pandas as pd
import numpy as np

In [3]:
np.random.rand(3,5)

array([[0.68758854, 0.46340086, 0.91654756, 0.58486585, 0.95034952],
       [0.00099778, 0.54059229, 0.05856465, 0.53800374, 0.04053218],
       [0.67572506, 0.32319567, 0.7223315 , 0.27310924, 0.15480459]])

In [4]:
rando_mat=np.random.rand(3,5)
rando_mat

array([[0.63100404, 0.01530532, 0.76096197, 0.27633215, 0.10611862],
       [0.60425478, 0.13630004, 0.55678692, 0.42796536, 0.14927617],
       [0.84978485, 0.17250028, 0.89414867, 0.25751796, 0.35204975]])

In [5]:
np.random.seed(32)

#임의로 유저 취향과 상품 속성 행렬 생성하는 함수
def initialize(R,num_features):
  #유저 취향: 유저 데이터 개수 * 속성개수차원(k) 임의 행렬(random) >> 변수 theta 저장
  #상품속성 취향 : 속성개수차원(k) 임의행렬(random) * item(영화) 데이터 개수 차원(random) >> 변수 X 저장
  num_users, num_items=R.shape

  Theta=np.random.rand(num_users,num_features)
  X=np.random.rand(num_features,num_items)

  return Theta,X

In [6]:
#실제 값 행렬
R=np.array([
    [3,4,1,np.nan,1,2],
    [4,4,3,np.nan,5,3],
    [2,3,np.nan,1,3,4],
    [1,3,2,4,2,2],
    [1,2,np.nan,2,2,4]
])

In [7]:
Theta,X=initialize(R,2)
#초기화한 값

In [8]:
Theta,X

(array([[0.85888927, 0.37271115],
        [0.55512878, 0.95565655],
        [0.7366696 , 0.81620514],
        [0.10108656, 0.92848807],
        [0.60910917, 0.59655344]]),
 array([[0.09178413, 0.34518624, 0.66275252, 0.44171349, 0.55148779,
         0.70371249],
        [0.58940123, 0.04993276, 0.56179184, 0.76635847, 0.91090833,
         0.09290995]]))